### ISSUE TITLE
241 ring issues

### ISSUE THREAD

**Issue by netmindz** [ewoudwijma/StarMod#37] opened 2024-03-03 10:32 UTC
Default projection seems to fail to render some of the outer pixels using effects like octopus

**Comment by ewoudwijma** [comment] 2024-03-03 14:35
Noted as well, will be dealt with when refactoring projectionAndMap function

**Comment by ewoudwijma** [comment] 2024-03-03 16:34
Fixed. Circular fixture sizes too small due to rounding to floor.

To test, re generate fixtures used 

@softhack007 , you also noticed this

Can you check and let me know if the issue can be closed ?

**Comment by ewoudwijma** [comment] 2024-03-03 16:36
https://github.com/ewowi/StarMod/assets/1737159/678dcb6a-2104-4bd5-abe6-927a26f28552

**Comment by softhack007** [comment] 2024-03-04 13:52
> To test, re generate fixtures used
> @softhack007 , you also noticed this
> Can you check and let me know if the issue can be closed ?

Hi, yes just uploaded, and all leds light up now in my "ring93". 👍 

I have other problems afterwards as only "rainbow" and "solid" seem to work - fixture stays dark with other effects i've tried. maybe that's another bug.

**Comment by ewoudwijma** [comment] 2024-03-04 15:05
Closed as it's confirmed to work fine now

**Closed as completed** 2024-03-04 15:05 UTC
